apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-avantis-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shivanshs9/node-argo-sample
    targetRevision: HEAD
    path: charts/avantis-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
