---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json

controllers:
  main:
    strategy: RollingUpdate
    rollingUpdate:
      unavailable: 1
      surge: 1
    replicas: 2
    containers:
      main:
        image:
          repository: shivanshs9/avantis-nodejs-sample
          tag: 1
          pullPolicy: IfNotPresent

service:
  main:
    controller: main
    ports:
      http:
        port: 8080
